options:
  cache-config: false
  merge-default-rules: true
rules:
  attribute-quotes:
    - 2
    - include: true
  border-zero:
    - 1
    - convention: 0
  brace-style:
    - 2
    - style: 1tbs
    - allow-single-line: false
  class-name-format:
    - 2
    - convention: hyphenatedlowercase
    - allow-leading-underscore: false

  clean-import-paths:
    - 2
    - leading-underscore: false
    - filename-extension: false
  empty-args:
    - 2
    - include: false
  empty-line-between-blocks:
    - 2
    - include: true
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 2
    - include: true
  force-attribute-nesting: 0
  force-element-nesting: 2
  force-pseudo-nesting: 0
  function-name-format:
    - 2
    - convention: hyphenatedlowercase
    - allow-leading-underscore: false

  hex-length:
    - 2
    - style: short
  hex-notation:
    - 2
    - style: uppercase
  id-name-format:
    - 2
    - convention: camelcase
    - allow-leading-underscore: false
  indentation:
    - 2
    - size: 2
  leading-zero:
    - 2
    - include: false
  mixin-name-format:
    - 2
    - convention: hyphenatedlowercase
    - allow-leading-underscore: false
  mixins-before-declarations:
    - 2
    - exclude:
      - breakpoint
      - mq
  nesting-depth:
    - 2
    - max-depth: 2
  no-attribute-selectors: 1
  no-color-hex: 0
  no-color-keywords: 2
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 1
  no-debug: 2
  no-empty-rulesets: 2
  no-extends: 1
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: true
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-universal-selectors: 2
  no-url-protocols: 2
  no-vendor-prefixes: 1
  no-warn: 2
  one-declaration-per-line: 2
  placeholder-in-extend: 2
  property-sort-order:
    - 2
    - order: 'alphabetical'
  property-units:
    - 2
    - global: ['px', 'rem']
  pseudo-element: 2
  quotes:
    - 2
    - style: single
  shorthand-values: 1
  single-line-per-selector: 2
  space-after-bang: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  variable-for-property: 2
  variable-name-format:
    - 2
    - convention: hyphenatedlowercase
    - allow-leading-underscore: false
  zero-unit: 2
