options:
  cache-config: false
  merge-default-rules: false
rules:
  border-zero:
    - 2
    - convention: '0'
  brace-style:
    - 2
    - style: 1tbs
    - allow-single-line: false
  class-name-format:
    - 2
    - convention: hyphenatedbem
    - allow-leading-underscore: false
  clean-import-paths:
    - 2
    - leading-underscore: false
    - filename-extension: false
  declarations-before-nesting: 2
  empty-line-between-blocks:
    - 2
    - include: true
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 2
    - include: true
  function-name-format:
    - 2
    - convention: hyphenatedlowercase
    - allow-leading-underscore: false
  hex-length:
    - 2
    - style: short
  hex-notation:
    - 2
    - style: uppercase
  id-name-format:
    - 2
    - convention: hyphenatedlowercase
    - allow-leading-underscore: false
  indentation:
    - 2
    - size: 2
  leading-zero:
    - 2
    - include: true
  mixin-name-format:
    - 2
    - convention: hyphenatedlowercase
    - allow-leading-underscore: false
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties:
      - 2
      - extra-properties:
        - overflow-scrolling
        - touch-callout
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  one-declaration-per-line : 2
  quotes:
    - 2
    - style: single
  shorthand-values: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  variable-name-format:
    - 2
    - convention: hyphenatedlowercase
    - allow-leading-underscore: false
  zero-unit: 2

  mixins-before-declarations: 1
  no-vendor-prefixes: 1
