options:
  cache-config: false
  merge-default-rules: false
rules:
  # target: error
  brace-style:
    - 1
    - style: 1tbs
    - allow-single-line: false
  class-name-format:
    - 1
    - convention: hyphenatedbem
    - allow-leading-underscore: false
  declarations-before-nesting: 1
  empty-line-between-blocks:
    - 1
    - include: true
  final-newline:
    - 1
    - include: true
  function-name-format:
    - 1
    - convention: hyphenatedlowercase
    - allow-leading-underscore: false
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 1
    - style: uppercase
  id-name-format:
    - 1
    - convention: hyphenatedlowercase
    - allow-leading-underscore: false
  indentation:
    - 1
    - size: 2
  mixin-name-format:
    - 1
    - convention: hyphenatedlowercase
    - allow-leading-underscore: false
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-invalid-hex: 1
  no-misspelled-properties: 1
  no-trailing-whitespace: 1
  one-declaration-per-line : 1
  quotes:
    - 1
    - style: single
  space-after-colon: 1
  space-after-comma: 1
  space-around-operator: 1
  space-before-bang: 1
  space-before-brace: 1
  space-before-colon: 1
  space-between-parens: 1
  trailing-semicolon: 1
  url-quotes: 1
  variable-name-format:
    - 1
    - convention: hyphenatedlowercase
    - allow-leading-underscore: false
  zero-unit: 1

  # target: warning
  border-zero:
    - 1
    - convention: '0'
  clean-import-paths:
    - 1
    - leading-underscore: false
    - filename-extension: false
  extends-before-declarations: 1
  extends-before-mixins: 1
  leading-zero:
    - 1
    - include: true
  mixins-before-declarations: 1
  no-attribute-selectors: 1
  no-mergeable-selectors: 1
  no-trailing-zero: 1
  no-vendor-prefixes: 1
  shorthand-values: 1
